### ISSUE TITLE
Add 9X5X chipset new bootloaders 

### ISSUE THREAD

**Issue by AliRazaManzoor** [bkerler/Loaders#10]
i have found huawei e5788 original bootloaders it is base upon qualcomm 9x5x chipset ,i try all bootloaders in your folder loaders/qualcomm/9x5x/enprg_9x55p.mbn it not work , so i have original bootloaders ,loader is attached please patch bootloaders and add in loader/qualcomm/9x5x/ folder .
[bootloaderimage_e5788.zip](https://github.com/bkerler/Loaders/files/8046746/bootloaderimage_e5788.zip)

**Comment by bkerler** [comment]
Done.
