### ISSUE TITLE
How do we identify loaders?

### ISSUE THREAD

**Issue by HikaruFox** [bkerler/Loaders#45]
As in title, how do we identify which loader is which?

**Comment by ninjaWolf8724** [comment]
need to know this too

**Comment by RenateUSB** [comment]
It's difficult.
First, look at the HWID that that edl.py prints out.
That will tell you the hardware.
Presumably edl.py has searched the library of loaders and not found anything.
If your device has SecureBoot then only a correctly signed Firehose loader will do.
If it does not have SecureBoot enabled then any compatible loader will do.

The loaders are organized in the library by HWID and the first 16 hexits of the hash.
You will find that some of them are identical to others with different names.
Internally, the loaders do not really go by HWID, but by model names, like SDM636, MSM8996 or QCS_AGATTI.
One of your first tasks is to find out what your HWID means as far a model *name*.
This could be the same text that your device gives out in `cat /proc/cpuinfo`. Or not.
Then you can simply try any loader that includes that name as a string internally.

**Comment by ninjaWolf8724** [comment]
Thanks

**Comment by bkerler** [comment]
Structure is msmid_pkhash[first 8 bytes]_[loadertype].bin
If you connect in 9008 mode with the edl tool, it will print the msmid and the pkhash.
