### ISSUE TITLE
Duplicate loaders

### ISSUE THREAD

**Issue by bbeaavr** [bkerler/Loaders#48]
`Loaders/t2mobile/000940e100420050_1357fdaeabb7becb_fhprg.bin` and `Loaders/hmd/000940e100420050_1357fdaeabb7becb_fhprg.bin` are the same file.

**Comment by RenateUSB** [comment]
There are at least 29 duplicated loaders.
Some of the duplicates have different filenames.
That's an artefact of how they are organized in directories.

**Comment by bkerler** [comment]
This is fixed in the current commit.
