### ISSUE TITLE
please explain how to use sdx55.mbn loader via qtools??

### ISSUE THREAD

**Issue by dr-h-ui** [bkerler/Loaders#51]
[Loaders](https://github.com/bkerler/Loaders/tree/b39741a9b96160755b963819d52dfe589f7a3a62)/[qualcomm](https://github.com/bkerler/Loaders/tree/b39741a9b96160755b963819d52dfe589f7a3a62/qualcomm)/[patched](https://github.com/bkerler/Loaders/tree/b39741a9b96160755b963819d52dfe589f7a3a62/qualcomm/patched)/sdx55m/

**Comment by aliraza4444** [comment]
how to use sdx55m.mbn loader in patched folder via qtools

**Comment by bkerler** [comment]
These loaders are not meant for qtools.
