### ISSUE TITLE
Please add mi watch msm8909w [baiji or baiji_sw name] loader

### ISSUE THREAD

**Issue by dslim666** [bkerler/Loaders#6]
What files for this need?
http://deviceinfohw.ru/devices/item.php?item=49947

**Comment by bkerler** [comment]
Done, use watch3100 loaders

**Comment by dslim666** [comment]
> Done, use watch3100 loaders

nowhere to be found on watch 3100

**Comment by dslim666** [comment]
From Huaway, oppo, mobvoi firehose not working

**Comment by dslim666** [comment]
![IMG20230408222206](https://user-images.githubusercontent.com/83533815/230729346-1cd2cb67-3c0a-423b-a123-48170fea01bb.jpg)
Not working

**Comment by dslim666** [comment]
And 
![Uploading IMG20230409130512.jpg…]()

**Comment by dslim666** [comment]
And 
![IMG20230409130512](https://user-images.githubusercontent.com/83533815/230757434-53371c98-1bbe-472d-a64a-8a9bb2512433.jpg)
