### ISSUE TITLE
How to grab firehose fiiles from my Pixel 4a

### ISSUE THREAD

**Issue by mizzunet** [bkerler/Loaders#68]
I have a running Pixel 4a. I can't seem to find firehose files anywhere on internet, in case my phone bricks. How can I grab firehose files and from my own device? I'd like to contribute to this repo.

Thanks

**Comment by RenateUSB** [comment]
The Firehose loader is not on your device.
Firehose loaders appear magically (or not) on the internet somehow.

**Comment by bkerler** [comment]
Yes right. Either they leak or not. So far, no firehose loaders ever leaked from google.
