### ISSUE TITLE
ZTE has duplicate loader, also ambiguous loader

### ISSUE THREAD

**Issue by RenateUSB** [bkerler/Loaders#80]
In ZTE there is both
Loaders-main\zte\009600E100040000_86c4f630cbc412fd_FHPRG_peek.bin
Loaders-main\zte\009600e100040000_86c4f630cbc412fd_fhprg_peek.bin
Which are identical.

In ZTE there is both
Loaders-main\zte\009720E100040000_4673478f4dd4d43c_FHPRG_peek.bin
Loaders-main\zte\009720e100040000_4673478f4dd4d43c_fhprg_peek.bin
Which are different. This causes problem with case-insensitive file systems.

There are 3 other loaders that have FHPRG instead of fhprg.

**Comment by bkerler** [comment]
Solved.
