### ISSUE TITLE
Guide on how to get loaders for my device which is not listed?

### ISSUE THREAD

**Issue by Z9044234820** [bkerler/Loaders#98]
@bkerler

**Comment by RenateUSB** [comment]
C'mon. Post some info at least. What's the HWID, what's the hash?

**Comment by Z9044234820** [comment]
HWID:              0x000a50e100300000 (MSM_ID:0x000a50e1,OEM_ID:0x0030,MODEL_ID:0x0000)
CPU detected:      "SM8150"
PK_HASH:           0xa92b7191e6328ed620f2b801deaed9d89fef98ae04accd89477fd2cf9203740cba2f500fb58e3f648962a872aa3f0a28

**Comment by RenateUSB** [comment]
Sorry, I don't see that hash anywhere.

**Comment by Z9044234820** [comment]
So no loader?

**Comment by RenateUSB** [comment]
Unless this does not have Secure Boot enabled there are no (to us) known loaders for it.
Since this is Haier, there is practically no chance that this does not have Secure Boot.

**Comment by Z9044234820** [comment]
It's not a Haier it's a HTC.

**Comment by Z9044234820** [comment]
So if my device has secure boot enabled then this EDL tool is ineffective/not going to work for my device?

**Comment by RenateUSB** [comment]
You could have supplied the info what this is in the first post.
What is this, twenty questions?

Well, some non-phones don't have Secure Boot enabled.
Is this rooted? Or do you have an update? Do you have the xbl?

**Comment by Z9044234820** [comment]
I booted into TWRP with fastboot boot recovery.img and within twrp I found /dev/block/by-name/xbl_a and /dev/block/by-name/xbl_b and both files are identical. I have locked bootloader, and it is not rooted but I still got into twrp with the fastboot command. Loader can be made with the xbl?

**Comment by RenateUSB** [comment]
I'm looking closely but I can't see that xbl from here.

**Comment by Z9044234820** [comment]
> I'm looking closely but I can't see that xbl from here.

What do you mean?

**Comment by RenateUSB** [comment]
I wanted to see this abl and I can't unless you post it.

**Comment by Z9044234820** [comment]
[xbl.zip](https://github.com/user-attachments/files/16197061/xbl.zip)

**Comment by RenateUSB** [comment]
Your abl has the same PK has as the EDL client is reporting.
That indicates it's highly probably that Secure Boot is enabled.

There is one more test. So, try this experiment.
Try to load some xbl's as if it were a Firehose loader.
It's not going to work as Firehose or even be able to boot.
But the original xbl that you posted should load 100% and then fail.
The modified version below should fail loading at 1 to 5%.

[unxbl.zip](https://github.com/user-attachments/files/16197372/unxbl.zip)

**Comment by Z9044234820** [comment]
Running `edl printgpt --loader unxbl.img --debugmode` (your unxbl) would return `DeviceClass - [LIB]: Timed out` 4 times before exiting, while running `edl printgpt --loader xbl.img --debugmode` (my xbl) would return infinite lines of `DeviceClass - USBError(19, 'No such device (it may have been disconnected)')` even when my device is properly connected. Does that mean secure boot is enabled?

**Comment by RenateUSB** [comment]
I can't tell anything from what you posted.
It was presumed that both would fail.
The question is, which completely loaded the "Firehose loader" before it died.

**Comment by Z9044234820** [comment]
Could you assist on how to change the `edl printgpt` (maybe change printgpt to something else, or add another parameter, etc.) command so it would show if the firehose loader is loaded or not?

**Comment by RenateUSB** [comment]
It's clear that this device has Secure Boot enabled.
The xbl says clearly "sahara - Loader successfully uploaded."
The unxbl disconnects when loading.
Everything after this is immaterial because I said it would not work using an xbl as a Firehose loader.

**Comment by Z9044234820** [comment]
So what is next? Now that it is found out that Secure boot is enabled, and that xbl loads and unxbl does not load, that means loader cannot be made? or can it be made?

**Comment by RenateUSB** [comment]
You have Secure Boot.
You need a Firehose loader that the hash matches.
There is no such loader available now.

**Comment by Z9044234820** [comment]
How to disable secure boot.

**Comment by RenateUSB** [comment]
You can't disable Secure Boot.
You would have to buy a new, unprogrammed processor and replace the chip.

**Comment by Z9044234820** [comment]
Where to find unprogrammed processor? The search returns phones with the processor, not the processor itself for sale.

**Comment by alltern** [comment]
THANKS FOR THIS RENATEUSB I just tried with the XBL too and it gets past the USBError19 and the loader is able to be uploaded. I now understand its just an issue with the loader! thanks I can now close that issue.
